### ISSUE TITLE
Question regarding validset

### ISSUE THREAD

**Issue by dain5832** [weitianxin/MACR#4]
Hi!
I wonder whether the valid set is included in test.txt.
In the paper, you mentioned that test data takes 10% of the entire data, but it seems like the data you've uploaded has more interactions than that. (For instance, gowalla has 1027370 interactions in total, and test data has 204905 interactions which is around 20% of the entire dataset)

If not, I would like to ask if I can get a code for the valid split.

Thanks!

**Comment by weitianxin** [comment]
Thank you for your inquiry. To obtain the experimental results, you can run the commands specified in the GitHub. Additionally, we have provided a script for generating the data split in the "utils/predata_valid.py" file. We originally didn't provide the valid split as there is little need to tune the hyperparameters of the method. However, you can split based on the need to perform any further analysis or experimentation. Thanks.

**Comment by dain5832** [comment]
Thanks a lot for your help :)

**Comment by dain5832** [comment]
Hi, I went through the code you mentioned, but I'm still a bit confused about how you configured the valid set.
To construct a valid set from the data you provide, should it be created in the test file or in the training file?
